name: scrape_supermarkets_uruguay
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  app_core:
    path: kit/app_core
  app_helpers:
    path: kit/app_helpers
  app_ui:
    path: kit/app_ui
  beautiful_soup_dart: ^0.3.0
  bloc: ^8.1.1
  cloud_firestore: ^5.6.0
  crypto: ^3.0.6
  device_info_plus: ^11.2.0
  equatable: ^2.0.7
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  firebase_messaging: ^15.2.0
  firebase_storage: ^12.3.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_facebook_auth: ^7.1.1
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.3
  freezed_annotation: ^2.4.4
  go_router: ^14.6.3
  google_sign_in: ^6.2.2
  image_cropper: ^8.1.0
  image_picker: ^1.1.2
  internet_connection_checker_plus: ^2.7.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  local_auth: ^2.3.0
  permission_handler: ^11.3.1
  reactive_forms: ^17.0.1
  result_dart: ^2.0.0
  shared_preferences: ^2.3.4
  sign_in_with_apple: ^6.1.4
  smooth_page_indicator: ^1.2.0+3
  timezone: ^0.10.0
  http: any
  url_launcher: ^6.3.1

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.3
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.0-0.0.dev
  json_serializable: ^6.6.2
  mocktail: ^1.0.4
  mockito: ^5.4.5
  very_good_analysis: ^7.0.0

dependency_overrides:
  analyzer: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
